/**
 * 	Parse Tree Printer is used for debugging by outputing a parse tree generated by "parse.h" and "parse.cpp"
 *	without comments
 */

#include <iostream>
#include <string>
#include "parse.h"
#define width 80
#define height 5
#define fieldwidth 10 

using namespace std;

string s;

ParseTree* tree;

char graph[500][500]={0};

int layerMax[100]={0};
int depth=0;

int main()
{
	gets(s);
	if (s[s.size()-1]=='\n')
		s.pop_back();

	tree = Parsing(s);

	dfs(tree, 0);

	for (int i=0; i<width; ++i)
	{
		for (int j=0; j<fieldwidth*layerMax[i]; ++j)
			if (graph[i][j]==0)
				cout << ' ';
			else
				cout << graph[i][j];
		cout << endl;

	}

	return 0;
}
